vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /media/images
            upload_destination: '%kernel.project_dir%/public/media/images'
            namer: vich_uploader.namer_smart_unique
