namespaces:
  entity: App\Entity
  enum: App\Enum
  interface: App\Model

types:
  # Parent class of Person
  Thing:
    properties:
      name: ~
  Person:
    parent: ~
    properties:
      email: { unique: true, nullable: false}
  ProjectStage:
    parent: \MyCLabs\Enum\Enum
    properties: {}
  Project:
    parent: false
    properties:
      name: { range: Text }
      stage: { range: ProjectStage }
      foreman: { range: Person, nullable: false}